name: vguard
description: A simple and fluent way to validate form or input data in Dart and Flutter.
version: 1.0.1

homepage: https://github.com/devv-thiago/vguard
repository: https://github.com/devv-thiago/vguard
issue_tracker: https://github.com/devv-thiago/vguard/issues

environment:
  sdk: ^3.6.0

# Regular dependencies
dependencies:
  # Add your package dependencies here

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
